//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.DateTime Deadline { get; set; }
        public bool ResolvesActivity { get; set; }
        public int ActivityId { get; set; }
        public bool Resolved { get; set; }
        public int Duration { get; set; }
        public string Notes { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
